.\" DO NOT MODIFY THIS FILE!  It was generated by help2man 1.48.5.
.\" I did it, anyway.

.TH ROC-SMI "1" "2022-01-30" "roc-smi 1.4.1" "User Commands"
.SH NAME
roc-smi - a tool to monitor AMD datacenter accelerators and GPUs
.SH SYNOPSIS
\fBroc\-smi\fR [\-h] [\-d DEVICE [DEVICE ...]] [\-\-alldevices] [\-\-showhw] [\-a] [\-i] [\-v] [\-e [EVENT ...]]
.IP
[\-\-showdriverversion] [\-\-showfwinfo [BLOCK ...]] [\-\-showmclkrange] [\-\-showmemvendor] [\-\-showsclkrange]
[\-\-showproductname] [\-\-showserial] [\-\-showuniqueid] [\-\-showvoltagerange] [\-\-showbus] [\-\-showpagesinfo]
[\-\-showpendingpages] [\-\-showretiredpages] [\-\-showunreservablepages] [\-f] [\-P] [\-t] [\-u] [\-\-showmemuse]
[\-\-showvoltage] [\-b] [\-c] [\-g] [\-l] [\-M] [\-m] [\-o] [\-p] [\-S] [\-s] [\-\-showmeminfo TYPE [TYPE ...]]
[\-\-showpids] [\-\-showpidgpus [SHOWPIDGPUS ...]] [\-\-showreplaycount] [\-\-showrasinfo [SHOWRASINFO ...]]
[\-\-showvc] [\-\-showxgmierr] [\-\-showtopo] [\-\-showtopoweight] [\-\-showtopohops] [\-\-showtopotype]
[\-\-showtoponuma] [\-\-showenergycounter] [\-r] [\-\-resetfans] [\-\-resetprofile] [\-\-resetpoweroverdrive]
[\-\-resetxgmierr] [\-\-resetperfdeterminism] [\-\-setclock LEVEL LEVEL] [\-\-setsclk LEVEL [LEVEL ...]]
[\-\-setmclk LEVEL [LEVEL ...]] [\-\-setpcie LEVEL [LEVEL ...]] [\-\-setslevel SCLKLEVEL SCLK SVOLT]
[\-\-setmlevel MCLKLEVEL MCLK MVOLT] [\-\-setvc POINT SCLK SVOLT] [\-\-setsrange SCLKMIN SCLKMAX]
[\-\-setmrange MCLKMIN MCLKMAX] [\-\-setfan LEVEL] [\-\-setperflevel LEVEL] [\-\-setoverdrive %]
[\-\-setmemoverdrive %] [\-\-setpoweroverdrive WATTS] [\-\-setprofile SETPROFILE] [\-\-setperfdeterminism SCLK]
[\-\-rasenable BLOCK ERRTYPE] [\-\-rasdisable BLOCK ERRTYPE] [\-\-rasinject BLOCK] [\-\-gpureset]
[\-\-load FILE | \fB\-\-save\fR FILE] [\-\-autorespond RESPONSE] [\-\-loglevel LEVEL] [\-\-json] [\-\-csv]
.PP
AMD ROCm System Management Interface | ROCM\-SMI version: 1.4.1 | Kernel version: 5.15.0\-3\-amd64
.SS "optional arguments:"
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-gpureset\fR
Reset specified GPU (One GPU must be specified)
.TP
\fB\-\-load\fR FILE
Load Clock, Fan, Performance and Profile settings from FILE
.TP
\fB\-\-save\fR FILE
Save Clock, Fan, Performance and Profile settings to FILE
.TP
\fB\-d\fR DEVICE [DEVICE ...], \fB\-\-device\fR DEVICE [DEVICE ...]
Execute command on specified device
.SS "Display Options:"
.HP
\fB\-\-alldevices\fR
.TP
\fB\-\-showhw\fR
Show Hardware details
.TP
\fB\-a\fR, \fB\-\-showallinfo\fR
Show Temperature, Fan and Clock values
.SS "Topology:"
.TP
\fB\-i\fR, \fB\-\-showid\fR
Show GPU ID
.TP
\fB\-v\fR, \fB\-\-showvbios\fR
Show VBIOS version
.TP
\fB\-e\fR [EVENT ...], \fB\-\-showevents\fR [EVENT ...]
Show event list
.TP
\fB\-\-showdriverversion\fR
Show kernel driver version
.TP
\fB\-\-showfwinfo\fR [BLOCK ...]
Show FW information
.TP
\fB\-\-showmclkrange\fR
Show mclk range
.TP
\fB\-\-showmemvendor\fR
Show GPU memory vendor
.TP
\fB\-\-showsclkrange\fR
Show sclk range
.TP
\fB\-\-showproductname\fR
Show SKU/Vendor name
.TP
\fB\-\-showserial\fR
Show GPU's Serial Number
.TP
\fB\-\-showuniqueid\fR
Show GPU's Unique ID
.TP
\fB\-\-showvoltagerange\fR
Show voltage range
.TP
\fB\-\-showbus\fR
Show PCI bus number
.SS "Pages information:"
.TP
\fB\-\-showpagesinfo\fR
Show retired, pending and unreservable pages
.TP
\fB\-\-showpendingpages\fR
Show pending retired pages
.TP
\fB\-\-showretiredpages\fR
Show retired pages
.TP
\fB\-\-showunreservablepages\fR
Show unreservable pages
.SS "Hardware-related information:"
.TP
\fB\-f\fR, \fB\-\-showfan\fR
Show current fan speed
.TP
\fB\-P\fR, \fB\-\-showpower\fR
Show current Average Graphics Package Power Consumption
.TP
\fB\-t\fR, \fB\-\-showtemp\fR
Show current temperature
.TP
\fB\-u\fR, \fB\-\-showuse\fR
Show current GPU use
.TP
\fB\-\-showmemuse\fR
Show current GPU memory used
.TP
\fB\-\-showvoltage\fR
Show current GPU voltage
.SS "Software-related/controlled information:"
.TP
\fB\-b\fR, \fB\-\-showbw\fR
Show estimated PCIe use
.TP
\fB\-c\fR, \fB\-\-showclocks\fR
Show current clock frequencies
.TP
\fB\-g\fR, \fB\-\-showgpuclocks\fR
Show current GPU clock frequencies
.TP
\fB\-l\fR, \fB\-\-showprofile\fR
Show Compute Profile attributes
.TP
\fB\-M\fR, \fB\-\-showmaxpower\fR
Show maximum graphics package power this GPU will consume
.TP
\fB\-m\fR, \fB\-\-showmemoverdrive\fR
Show current GPU Memory Clock OverDrive level
.TP
\fB\-o\fR, \fB\-\-showoverdrive\fR
Show current GPU Clock OverDrive level
.TP
\fB\-p\fR, \fB\-\-showperflevel\fR
Show current DPM Performance Level
.TP
\fB\-S\fR, \fB\-\-showclkvolt\fR
Show supported GPU and Memory Clocks and Voltages
.TP
\fB\-s\fR, \fB\-\-showclkfrq\fR
Show supported GPU and Memory Clock
.TP
\fB\-\-showmeminfo\fR TYPE [TYPE ...]
Show Memory usage information for given block(s) TYPE
.TP
\fB\-\-showpids\fR
Show current running KFD PIDs
.TP
\fB\-\-showpidgpus\fR [SHOWPIDGPUS ...]
Show GPUs used by specified KFD PIDs (all if no arg given)
.TP
\fB\-\-showreplaycount\fR
Show PCIe Replay Count
.TP
\fB\-\-showrasinfo\fR [SHOWRASINFO ...]
Show RAS enablement information and error counts for the
specified block(s) (all if no arg given)
.TP
\fB\-\-showvc\fR
Show voltage curve
.TP
\fB\-\-showxgmierr\fR
Show XGMI error information since last read
.TP
\fB\-\-showtopo\fR
Show hardware topology information
.TP
\fB\-\-showtopoweight\fR
Shows the relative weight between GPUs
.TP
\fB\-\-showtopohops\fR
Shows the number of hops between GPUs
.TP
\fB\-\-showtopotype\fR
Shows the link type between GPUs
.TP
\fB\-\-showtoponuma\fR
Shows the numa nodes
.TP
\fB\-\-showenergycounter\fR
Energy accumulator that stores amount of energy consumed
.SS "Set options:"
.TP
\fB\-\-resetperfdeterminism\fR
Disable performance determinism
.TP
\fB\-\-setclock\fR LEVEL LEVEL
Set Clock Frequency Level(s) for specified clock (requires
manual Perf level)
.TP
\fB\-\-setsclk\fR LEVEL [LEVEL ...]
Set GPU Clock Frequency Level(s) (requires manual Perf level)
.TP
\fB\-\-setmclk\fR LEVEL [LEVEL ...]
Set GPU Memory Clock Frequency Level(s) (requires manual Perf
level)
.TP
\fB\-\-setpcie\fR LEVEL [LEVEL ...]
Set PCIE Clock Frequency Level(s) (requires manual Perf level)
.TP
\fB\-\-setslevel\fR SCLKLEVEL SCLK SVOLT
Change GPU Clock frequency (MHz) and Voltage (mV) for a specific
Level
.TP
\fB\-\-setmlevel\fR MCLKLEVEL MCLK MVOLT
Change GPU Memory clock frequency (MHz) and Voltage for (mV) a
specific Level
.TP
\fB\-\-setvc\fR POINT SCLK SVOLT
Change SCLK Voltage Curve (MHz mV) for a specific point
.TP
\fB\-\-setsrange\fR SCLKMIN SCLKMAX
Set min and max SCLK speed
.TP
\fB\-\-setmrange\fR MCLKMIN MCLKMAX
Set min and max MCLK speed
.TP
\fB\-\-setfan\fR LEVEL
Set GPU Fan Speed (Level or %)
.TP
\fB\-\-setperflevel\fR LEVEL
Set Performance Level
.TP
\fB\-\-setoverdrive\fR %
Set GPU OverDrive level (requires manual|high Perf level)
.TP
\fB\-\-setmemoverdrive\fR %
Set GPU Memory Overclock OverDrive level (requires manual|high
Perf level)
.TP
\fB\-\-setpoweroverdrive\fR WATTS
Set the maximum GPU power using Power OverDrive in Watts
.TP
\fB\-\-setprofile\fR SETPROFILE
Specify Power Profile level (#) or a quoted string of CUSTOM
Profile attributes "# # # #..." (requires manual Perf level)
.TP
\fB\-\-setperfdeterminism\fR SCLK
Set clock frequency limit to get minimal performance variation
.TP
\fB\-\-rasenable\fR BLOCK ERRTYPE
Enable RAS for specified block and error type
.TP
\fB\-\-rasdisable\fR BLOCK ERRTYPE
Disable RAS for specified block and error type
.TP
\fB\-\-rasinject\fR BLOCK
Inject RAS poison for specified block (ONLY WORKS ON UNSECURE
BOARDS)
.SS "Reset options:"
.TP
\fB\-r\fR, \fB\-\-resetclocks\fR
Reset clocks and OverDrive to default
.TP
\fB\-\-resetfans\fR
Reset fans to automatic (driver) control
.TP
\fB\-\-resetprofile\fR
Reset Power Profile back to default
.TP
\fB\-\-resetpoweroverdrive\fR
Set the maximum GPU power back to the device deafult state
.TP
\fB\-\-resetxgmierr\fR
Reset XGMI error count
.SS "Auto-response options:"
.TP
\fB\-\-autorespond\fR RESPONSE
Response to automatically provide for all prompts (NOT
RECOMMENDED)
.SS "Output options:"
.TP
\fB\-\-loglevel\fR LEVEL
How much output will be printed for what program is doing, one
of debug/info/warning/error/critical
.TP
\fB\-\-json\fR
Print output in JSON format
.TP
\fB\-\-csv\fR
Print output in CSV format
.SH "SEE ALSO"
The full documentation for
.B roc-smi
is maintained as a Texinfo manual.  If the
.B info
and
.B roc-smi
programs are properly installed at your site, the command
.IP
.B info roc-smi
.PP
should give you access to the complete manual.
